{-# LANGUAGE LambdaCase          #-}
{-# LANGUAGE PatternSynonyms     #-}
{-# LANGUAGE ScopedTypeVariables #-}

-- | Experimental \"compiling to categories\" HVM2 backend, patterned on the
-- agda branch's ConCat integration (@agda:ctc/src/HVM.hs@). Where the ConCat
-- GHC plugin categorifies Haskell *source* into a @Bnd@ combinator term
-- rendered against a Bend combinator prelude, this module hand-writes the
-- corresponding functor from telomare's sized 'CompiledExpr' into the same
-- term language — the plugin itself cannot consume a runtime AST value.
--
-- The interpretation is the standard CCC reading of telomare's env-machine:
--
--   * a term denotes a morphism @env ⇨ value@ over one universal domain TV;
--   * @Env@ = 'idC' (identity), @Zero@ = 'zeroC' (constant);
--   * @Pair a b@ = @forkD(a, b)@ — the fork ⟨a,b⟩ followed by the data
--     embedding; @PLeft@/@PRight@ = projections post-composed via @comp@;
--   * @Defer body@ = @deferC(body)@ — curry: the body morphism becomes a
--     first-class closure value @TV/L{f: TV -> TV}@;
--   * @SetEnv x@ = @comp(applyD, x)@ — apply;
--   * the GateSwitch shape = @iteD(l, r, s)@ (native match on the
--     scrutinee, lazy arms).
--
-- CRUCIAL DIFFERENCE from 'Telomare.HvmBackend': closures are REAL Bend
-- lambdas flowing through data (no defunctionalization, no dispatch table).
-- That is the faithful categorical semantics — and exactly the pattern that
-- HVM2 runtimes are known to mishandle for non-affine duplication (church
-- towers). This backend exists to measure where that breaks; see
-- bend/PORT.md.
--
-- A second known cost: the emitted term is a TREE. Shared Defer bodies
-- (identical per 'FunctionIndex') are re-rendered at every occurrence, so
-- program text can blow up where the direct backend's named @d\<slot\>@
-- definitions stay linear.
module Telomare.HvmBackendCcc where

import Data.Fix (Fix (..))
import Data.List (intercalate)
import Telomare

-- | A Bend combinator-application term (as in agda:ctc/src/HVM.hs):
-- point-free, so no shared variables.
data Bnd = Atom String | App String [Bnd]

renderBnd :: Bnd -> String
renderBnd (Atom s)     = s
renderBnd (App s [])   = s
renderBnd (App s args) = s <> "(" <> intercalate ", " (map renderBnd args) <> ")"

-- ---------------------------------------------------------------------------
-- the functor: CompiledExpr -> Bnd
-- ---------------------------------------------------------------------------

toCat :: CompiledExpr -> Bnd
toCat = \case
  ZeroB -> Atom "zeroC"
  EnvB -> Atom "idC"
  PairB a b -> App "forkD" [toCat a, toCat b]
  LeftB x -> App "comp" [Atom "exlD", toCat x]
  RightB x -> App "comp" [Atom "exrD", toCat x]
  StuckEE (DeferSF _ body) -> App "deferC" [toCat body]
  SetEnvB (PairB (GateB l r) s) -> App "iteD" [toCat l, toCat r, toCat s]
  SetEnvB (PairB AbortB e) -> App "comp" [Atom "abortD", toCat e]
  SetEnvB x -> App "comp" [Atom "applyD", toCat x]
  AbortEE (AbortedF v) -> App "constC" [Atom (renderBasic v)]
  -- bare Abort/Gate outside their SetEnv shapes are not produced
  AbortB -> Atom "poisonC"
  GateB _ _ -> Atom "poisonC"
  _ -> error "HvmBackendCcc.toCat: unexpected CompiledExpr constructor"

renderBasic :: BasicExpr -> String
renderBasic = \case
  Fix ZeroSF -> "TV/Z"
  Fix (PairSF a b) -> "TV/P(" <> renderBasic a <> ", " <> renderBasic b <> ")"

-- ---------------------------------------------------------------------------
-- program assembly (same driver contract as Telomare.HvmBackend: the shell
-- driver appends `def inputs()` per run and decodes main()'s String result)
-- ---------------------------------------------------------------------------

emitProgramCcc :: CompiledExpr -> String
emitProgramCcc sized =
  cccPrelude
  <> "def tel_main() -> TV:\n  m = "
  <> renderBnd (toCat sized)
  <> "\n  return m(TV/Z)\n\n"
  <> cccDriver

cccPrelude :: String
cccPrelude = unlines
  [ "# generated by telomare --emit-hvm-ccc (src/Telomare/HvmBackendCcc.hs) -- do not edit"
  , "# ConCat-style combinator prelude: closures are native lambdas (TV/L),"
  , "# no defunctionalization. Patterned on agda:ctc/src/HVM.hs bendPrelude."
  , ""
  , "type TV:"
  , "  Z"
  , "  P { f: TV, s: TV }"
  , "  L { f: TV -> TV }"
  , "  A { p: TV }"
  , ""
  , "def idC(e: TV) -> TV:"
  , "  return e"
  , ""
  , "def zeroC(e: TV) -> TV:"
  , "  return TV/Z"
  , ""
  , "def poisonC(e: TV) -> TV:"
  , "  return TV/A(TV/Z)"
  , ""
  , "def constC(k: TV) -> (TV -> TV):"
  , "  return lambda e: k"
  , ""
  , "def comp(g: TV -> TV, f: TV -> TV) -> (TV -> TV):"
  , "  return lambda x: g(f(x))"
  , ""
  , "# fork ⟨f,g⟩ followed by the data embedding D×D -> D"
  , "def forkD(f: TV -> TV, g: TV -> TV) -> (TV -> TV):"
  , "  return lambda e: TV/P(f(e), g(e))"
  , ""
  , "# curry: the body morphism becomes a first-class closure value"
  , "def deferC(f: TV -> TV) -> (TV -> TV):"
  , "  return lambda e: TV/L(f)"
  , ""
  , "def exlD(v: TV) -> TV:"
  , "  match v:"
  , "    case TV/Z:"
  , "      return TV/Z"
  , "    case TV/P:"
  , "      return v.f"
  , "    case TV/A:"
  , "      return TV/A(v.p)"
  , "    case TV/L:"
  , "      return TV/A(TV/Z)"
  , ""
  , "def exrD(v: TV) -> TV:"
  , "  match v:"
  , "    case TV/Z:"
  , "      return TV/Z"
  , "    case TV/P:"
  , "      return v.s"
  , "    case TV/A:"
  , "      return TV/A(v.p)"
  , "    case TV/L:"
  , "      return TV/A(TV/Z)"
  , ""
  , "# truncate to the Zero/Pair skeleton (abortStep payload rule)"
  , "def tvTrunc(v: TV) -> TV:"
  , "  match v:"
  , "    case TV/Z:"
  , "      return TV/Z"
  , "    case TV/P:"
  , "      return TV/P(tvTrunc(v.f), tvTrunc(v.s))"
  , "    case TV/A:"
  , "      return TV/Z"
  , "    case TV/L:"
  , "      return TV/Z"
  , ""
  , "# FillFunction Abort x — abortStep: Zero selects the identity closure"
  , "def abortD(v: TV) -> TV:"
  , "  match v:"
  , "    case TV/Z:"
  , "      return TV/L(lambda x: x)"
  , "    case TV/P:"
  , "      return TV/A(tvTrunc(TV/P(v.f, v.s)))"
  , "    case TV/A:"
  , "      return TV/A(v.p)"
  , "    case TV/L:"
  , "      return TV/A(TV/Z)"
  , ""
  , "# apply: SetEnv on an evaluated pair (code, env)"
  , "def applyD(v: TV) -> TV:"
  , "  match v:"
  , "    case TV/P:"
  , "      code = v.f"
  , "      match code:"
  , "        case TV/L:"
  , "          return code.f(v.s)"
  , "        case TV/A:"
  , "          return TV/A(code.p)"
  , "        case TV/Z:"
  , "          return TV/A(TV/Z)"
  , "        case TV/P:"
  , "          return TV/A(TV/Z)"
  , "    case TV/A:"
  , "      return TV/A(v.p)"
  , "    case TV/Z:"
  , "      return TV/A(TV/Z)"
  , "    case TV/L:"
  , "      return TV/A(TV/Z)"
  , ""
  , "# GateSwitch: native match on the scrutinee value, lazy arms"
  , "def iteDH(l: TV -> TV, r: TV -> TV, sv: TV, e: TV) -> TV:"
  , "  match sv:"
  , "    case TV/Z:"
  , "      return l(e)"
  , "    case TV/P:"
  , "      return r(e)"
  , "    case TV/A:"
  , "      return TV/A(sv.p)"
  , "    case TV/L:"
  , "      return TV/A(TV/Z)"
  , ""
  , "def iteD(l: TV -> TV, r: TV -> TV, s: TV -> TV) -> (TV -> TV):"
  , "  return lambda e: iteDH(l, r, s(e), e)"
  , ""
  , "# closure call with telomare's appB convention: the callee is a closure"
  , "# Pair(code, captured); the body runs with env = (arg, captured)."
  , "def tvCall(c: TV, i: TV) -> TV:"
  , "  match c:"
  , "    case TV/P:"
  , "      code = c.f"
  , "      match code:"
  , "        case TV/L:"
  , "          return code.f(TV/P(i, c.s))"
  , "        case TV/A:"
  , "          return TV/A(code.p)"
  , "        case TV/Z:"
  , "          return TV/A(TV/Z)"
  , "        case TV/P:"
  , "          return TV/A(TV/Z)"
  , "    case TV/A:"
  , "      return TV/A(c.p)"
  , "    case TV/Z:"
  , "      return TV/A(TV/Z)"
  , "    case TV/L:"
  , "      return TV/A(TV/Z)"
  , ""
  ]

cccDriver :: String
cccDriver = unlines
  [ "# ---- driver ----"
  , ""
  , "def tv_b2i(v: TV, acc: u24) -> (u24, u24):"
  , "  match v:"
  , "    case TV/Z:"
  , "      return (1, acc)"
  , "    case TV/P:"
  , "      match sv0 = v.s:"
  , "        case TV/Z:"
  , "          return tv_b2i(v.f, acc + 1)"
  , "        case TV/P:"
  , "          return (0, 0)"
  , "        case TV/A:"
  , "          return (0, 0)"
  , "        case TV/L:"
  , "          return (0, 0)"
  , "    case TV/A:"
  , "      return (0, 0)"
  , "    case TV/L:"
  , "      return (0, 0)"
  , ""
  , "def tv_b2s(v: TV) -> String:"
  , "  match v:"
  , "    case TV/Z:"
  , "      return \"\""
  , "    case TV/P:"
  , "      (ok, c) = tv_b2i(v.f, 0)"
  , "      if ok:"
  , "        return String/Cons(c, tv_b2s(v.s))"
  , "      else:"
  , "        return \"\""
  , "    case TV/A:"
  , "      return \"\""
  , "    case TV/L:"
  , "      return \"\""
  , ""
  , "def sc(a: String, b: String) -> String:"
  , "  match a:"
  , "    case String/Nil:"
  , "      return b"
  , "    case String/Cons:"
  , "      return String/Cons(a.head, sc(a.tail, b))"
  , ""
  , "def one_iter(inp: TV) -> (String, TV, u24):"
  , "  r = tvCall(tel_main(), inp)"
  , "  match r:"
  , "    case TV/P:"
  , "      disp = tv_b2s(r.f)"
  , "      match nsv0 = r.s:"
  , "        case TV/Z:"
  , "          return (disp, TV/Z, 2)"
  , "        case TV/P:"
  , "          return (disp, TV/P(nsv0.f, nsv0.s), 1)"
  , "        case TV/A:"
  , "          return (disp, TV/Z, 0)"
  , "        case TV/L:"
  , "          return (disp, TV/L(nsv0.f), 1)"
  , "    case TV/A:"
  , "      return (\"aborted\", TV/Z, 0)"
  , "    case TV/Z:"
  , "      return (\"aborted\", TV/Z, 0)"
  , "    case TV/L:"
  , "      return (\"runtime error\", TV/Z, 0)"
  , ""
  , "def loop_go(state: TV, first: u24, ins: List(TV), acc: String) -> String:"
  , "  if first:"
  , "    (disp, ns, ok) = one_iter(TV/Z)"
  , "    return loop_cont(disp, ns, ok, ins, acc)"
  , "  else:"
  , "    match ins:"
  , "      case List/Nil:"
  , "        return acc"
  , "      case List/Cons:"
  , "        (disp, ns, ok) = one_iter(TV/P(ins.head, state))"
  , "        return loop_cont(disp, ns, ok, ins.tail, acc)"
  , ""
  , "def loop_cont(disp: String, ns: TV, ok: u24, rest: List(TV), acc: String) -> String:"
  , "  new_acc = sc(acc, sc(disp, \"\\n\"))"
  , "  switch ok:"
  , "    case 0:"
  , "      return new_acc"
  , "    case 1:"
  , "      return loop_go(ns, 0, rest, new_acc)"
  , "    case _:"
  , "      return new_acc"
  , ""
  , "def main() -> String:"
  , "  return sc(loop_go(TV/Z, 1, inputs(), \"\"), \"\")"
  ]
