-- Regenerate test/programs/tictactoe.tel2. This is fixture generation only;
-- neither the .tel2 compiler nor runtime contains tic-tac-toe semantics.
import qualified Data.Set as Set

type Board = String

main :: IO ()
main = writeFile "test/programs/tictactoe.tel2" . unlines $
  [ "# Generated by design/generate-tictactoe.hs"
  , "# A declarative finite machine; X (Player 1) moves first."
  , "telomare-finite-machine 1"
  , "initial " <> show (key empty 'X')
  , "global \"q\" stop \"Goodbye.\\n\""
  ] <> concatMap stateLines (reachable [(empty, 'X')] Set.empty)

empty :: Board
empty = replicate 9 '.'

key :: Board -> Char -> String
key board player = board <> [player]

reachable :: [(Board, Char)] -> Set.Set String -> [(Board, Char)]
reachable [] _ = []
reachable (state@(board, player) : queue) seen
  | Set.member stateKey seen = reachable queue seen
  | otherwise = state : reachable (queue <> children) (Set.insert stateKey seen)
  where
    stateKey = key board player
    children =
      [ (board', other player)
      | square <- [0 .. 8]
      , board !! square == '.'
      , let board' = place square player board
      , not (winner board' player)
      , '.' `elem` board'
      ]

stateLines :: (Board, Char) -> [String]
stateLines (board, player) =
  ["state " <> show (key board player) <> " " <> show (display board player)]
  <> fmap move [0 .. 8]
  <> ["default stay \"Invalid input; enter 1-9 or q.\\n\""]
  where
    move square
      | board !! square /= '.' = on square "stay \"That square is occupied.\\n\""
      | winner board' player = on square ("stop " <> show (renderBoard board' <> winMessage player))
      | '.' `notElem` board' = on square ("stop " <> show (renderBoard board' <> "Tie game.\n"))
      | otherwise = on square ("goto " <> show (key board' (other player)))
      where board' = place square player board
    on square target = "on " <> show (show (square + 1)) <> " " <> target

display :: Board -> Char -> String
display board player = renderBoard board
  <> "Player " <> playerNumber player <> "/" <> [player] <> " to move.\n"
  <> "Move (1-9 or q): "

renderBoard :: Board -> String
renderBoard board = row 0 <> "-+-+-\n" <> row 3 <> "-+-+-\n" <> row 6
  where
    row n = [cell n, '|', cell (n + 1), '|', cell (n + 2), '\n']
    cell n = if board !! n == '.' then head (show (n + 1)) else board !! n

winMessage :: Char -> String
winMessage player = "Player " <> playerNumber player <> "/" <> [player] <> " wins!\n"

playerNumber :: Char -> String
playerNumber 'X' = "1"
playerNumber _ = "2"

other :: Char -> Char
other 'X' = 'O'
other _ = 'X'

place :: Int -> Char -> Board -> Board
place square player board = take square board <> [player] <> drop (square + 1) board

winner :: Board -> Char -> Bool
winner board player = any (all ((== player) . (board !!)))
  [ [0, 1, 2], [3, 4, 5], [6, 7, 8]
  , [0, 3, 6], [1, 4, 7], [2, 5, 8]
  , [0, 4, 8], [2, 4, 6]
  ]
