name: Telomare CI

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v25
        with:
          install_url: https://releases.nixos.org/nix/nix-2.31.5/install
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v14
        with:
          name: telomare
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          extraPullNames: nix-community
      - name: Build and test
        run: |
          nix -Lv flake check
          nix -Lv develop -c cabal update
          nix -Lv develop -c cabal test telomare-test
          nix -Lv develop -c agda --safe spec/Everything.agda

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v25
        with:
          install_url: https://releases.nixos.org/nix/nix-2.31.5/install
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v14
        with:
          name: telomare
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          extraPullNames: nix-community
      - name: Format and lint
        run: nix run .#format-lint
