name: "Telomare CI Tests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v2.3.4
    - uses: actions/checkout@v2
      with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        # nix_path: nixpkgs=channel:nixos-unstable
        # skip_adding_nixpkgs_channel: true
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v8
      with:
        name: telomare
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # This might be overkill: telomare cache could be enough.
    - run: cachix use iohk
    - run: nix build .#telomare:exe:telomare-exe
    - run: nix run .#telomare:test:telomare-test
    - run: nix run .#telomare:test:telomare-parser-test
    - run: nix run .#telomare:test:telomare-serializer-test
